pi@piHenri:~/Documents/Distributeur/Arduino/GlobalArduino/v1 $ cat Makefile
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS =
USER_LIB_PATH = /home/pi/Arduino/libraries
include /usr/share/arduino/Arduino.mk


