#!/usr/bin/env python3
# coding: utf-8

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk,Gdk,Gio

class GrilleAvecBoutons(Gtk.Grid):
    def __init__(self):
        Gtk.Grid.__init__(self)

        btn = Gtk.Button(label="Mon super bouton")
        self.attach(btn,0, 0, 1, 1)
        
class MainWindow(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self)
        self.connect('delete-event', Gtk.main_quit)
        box = Gtk.Box()
        sublayout = GrilleAvecBoutons()

        box.pack_start(sublayout, True, True, 0)
        self.add(box)
        self.show_all()


app=MainWindow()
Gtk.main()
